### ISSUE TITLE
Failure trying to install on OS X Chrome Version 46.0.2490.71 (64-bit)

### ISSUE THREAD

**Issue by packplusplus** [gitlon/CASTER#2]
![screen shot 2015-10-22 at 7 48 19 pm](https://cloud.githubusercontent.com/assets/1477148/10681309/f190dae8-78f5-11e5-8d24-fa58b8e8bf20.png)

Was really excited to try this, but I'm getting the above error when I try to install.

**Comment by robizz** [comment]
Please fix this!
same problem in chrome Version 47.0.2526.80 (64-bit) on Debian 8

Cheers man great work!

**Comment by gunzy83** [comment]
Same issue with Version 48.0.2564.116 Ubuntu 15.10 (64-bit)

**Comment by gitlon** [comment]
Fixed in the latest version (v1.0.13) I believe, via pull-request.

**Comment by packplusplus** [comment]
Closing, I lost context of if this is still an issue and don't want to clutter up the issues history.
